### ISSUE TITLE
prod build with mirage enabled fails

### ISSUE THREAD

**Issue by CezaryH** [samselikoff/ember-cli-mirage#1339] opened 2018-07-04 13:11 UTC
I'm using ember version 3.1.4 with ember-cli-mirage 0.4.1,
unfortunately enabling mirage in prod build end with an error
```
Build failed.
Build Error (BabiliPlugin)

assets/vendor.js: Cannot convert undefined or null to object
```

**Comment by jamesarosen** [comment] 2018-07-31 17:56
Possibly the same as #1211

**Comment by samselikoff** [comment] 2018-08-10 20:42
Confirm, cannot reproduce on a new ember/mirage app.

Closing for now, @CezaryH please reopen if you're still having trouble!

**Closed by samselikoff** 2018-08-10 20:42 UTC
Labels: Bug
