### ISSUE TITLE
Mirage acceptance tests not working with ember-cli-babel includePolyfill enabled

### ISSUE THREAD

**Issue by bsaff** [samselikoff/ember-cli-mirage#1084] opened 2017-05-12 15:40 UTC
So I've got a very interesting error here. My steps: 

- Started a new ember app (ember-cli 2.13.1)
- Generated an acceptance test for visting '/'. 
- Verified that all tests pass. 
- Installed ember-cli-mirage. 
- Verified all tests still pass. 
- In ember-cli-build.js set babel's includePolyfill setting to `true`. 
- Run tests

**Results**: A  series of tests break with the following error appearing
```
not ok 23 PhantomJS 2.1 - Global error: Error:
TypeError: Object is not a constructor (evaluating '(0, _lodash_defineProperty['default'])') at http://localhost:7357/assets/test-support.js, line 6993
    ---
        Log: |
            { type: 'error',
              text: 'Error: \nTypeError: Object is not a constructor (evaluating \'(0, _lodash_defineProperty[\'default\'])\') at http://localhost:7357/assets/test-support.js, line 6993\n' }
```

**Comment by rwjblue** [comment] 2017-05-12 15:48
Seems good to have an issue over here also, but I believe this the same as https://github.com/ember-cli/ember-cli/issues/7001 and https://github.com/mike-north/ember-lodash/issues/103.

**Comment by bsaff** [comment] 2017-05-12 16:13
My workaround for now, haven't tested with a deploy yet but in theory should be okay. 
```javascript
module.exports = function(defaults) {
  var env = EmberApp.env();
  // enable polyfill as long as we are not testing
  var notTesting = env != 'test';
  var app = new EmberApp(defaults, {
    'ember-cli-babel': {
      includePolyfill: notTesting
    }
  });
...
```

**Comment by simonihmig** [comment] 2017-05-12 16:27
@bsaff I don't think that workaround is applicable in general. If you don't need the polyfill for PhantomJS, you certainly don't need it for any real browser then. Maybe this is working for you, because your tests are not touching your code that depends on the polypill?

**Comment by bsaff** [comment] 2017-05-12 16:48
@simonihmig that's true. currently not testing polyfill-dependent features. I'll make a note

**Comment by vmalloc** [comment] 2017-05-15 17:15
Also hitting this issue. Any news on how to avoid it?

**Comment by stefanpenner** [comment] 2017-05-15 20:12
@vmalloc look slike @rwjblue merged a fixed.

**Comment by simonihmig** [comment] 2017-05-15 20:17
This may be needed to get merged as well: https://github.com/mike-north/ember-lodash/pull/105

**Comment by fushi** [comment] 2017-05-15 23:11
Pretty sure this is a dupe of https://github.com/ember-cli/ember-cli/issues/7001

**Closed** 2017-05-18 12:09 UTC
