### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by ming-codes** [samselikoff/ember-cli-mirage#1211] opened 2017-11-06 09:01 UTC
```
Super expression must either be null or a function
```

I got a strange bug. It seems to only happen in production minified builds and the bug manifests only in `0.4.0`. `0.3.4` works fine.

The error itself is thrown from Babel generated code. From what I have gathered from the trace, it may have something to do with this https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/utils/extend.js#L7-L15

If `Super` in here is `undefined`, it could lead to an error, because you can't extend `undefined`.

Related PR here https://github.com/samselikoff/ember-cli-mirage/pull/1187/files

**Comment by cowboyd** [comment] 2018-01-04 19:18
@ming-codes Do you know if it is `undefined`? I don't see how it could be since it has to be invoked as:

```
Superclass.extend(properties)
```

What happens if you monkey patch it to say?

```js
let Parent = this || Object;
```

Is this still an issue?

**Comment by JohnnyBushy** [comment] 2018-01-19 13:32
Can't upgrade on 0.4.0 due to this bug. 
How can I help? :)

**Comment by jamesarosen** [comment] 2018-05-14 23:44
> What happens if you monkey patch it to say `let Parent = this || Object;`?

That seems to work!

**Comment by jamesarosen** [comment] 2018-05-15 00:10
I'm not sure `|| Object` is the right thing to do, though. The problem comes here:
```js
// ember-cli-mirage/serializers/active-model-serializer
export default Serializer.extend({
```
If we `|| Object`, then `ActiveModelSerializer` won't inherit from `Serializer`.

**Comment by jamesarosen** [comment] 2018-05-15 23:07
For now, I've "fixed" this by disabling minification:
```js
// ember-cli-build
'ember-cli-uglify': {
  enabled: false,
},
```

**Comment by samselikoff** [comment] 2018-07-28 15:08
I am not seeing this error in a new app running `0.4.0` (I was trying to first reproduce, and then see if the issue was still present in `0.4.7`.

Could someone tell me what setup/feature is needed in Mirage to trigger the bug?

**Comment by jamesarosen** [comment] 2018-07-30 18:54
I just tried 0.4.0 and 0.4.7. Both seemed fine. I wonder whether `ember-cli-uglify` has changed.

**Comment by samselikoff** [comment] 2018-08-10 20:43
I'm going to close this for now as I'm not able to reproduce.

If anyone is still having issues, please ping here and we can reopen!

**Closed by samselikoff** 2018-08-10 20:43 UTC
Labels: Needs more information

**Comment by kushthedude** [comment] 2019-12-29 10:15
I am still facing this issue , However I experience it while I was migrating to ES6 class.
I wrote 
```js
export default Mixin.create(MutableArray, CustomFormMixin, {
```
 as
  ```js
export default class extends Mixin.create(MutableArray, CustomFormMixin) {
```
Any help is highly appreciated

**Comment by samselikoff** [comment] 2020-01-06 19:52
@kushthedude those don't look like mirage APIs. Does your issue have anything to do with Mirage?
