### ISSUE TITLE
Config isn't loaded with mocha

### ISSUE THREAD

**Issue by GCorbel** [samselikoff/ember-cli-mirage#1396] opened 2018-10-12 16:25 UTC
I have this simple test : 

```
import { describe, it, beforeEach, afterEach } from 'mocha';
import startApp from 'form/tests/helpers/start-app';
import destroyApp from 'form/tests/helpers/destroy-app';
import { setupApplicationTest } from 'ember-mocha';
import setupMirage from 'ember-cli-mirage/test-support/setup-mirage';

describe('Acceptance | subscription', function() {
  setupApplicationTest();
  setupMirage();
  let application;

  beforeEach(function() {
    application = startApp();
  });

  afterEach(function() {
    destroyApp(application);
  });

  it('can fill a form', async function() {
    await visit('/subscription');
  });
});
```

And I have this config file : 

```
export default function() {
  this.get('/forms');
}
```

When I run the test I have `Your Ember app tried to GET '/forms' ...`.

The solution I found is to add `import mirageConfig from 'form/mirage/config';` and do `this.server.loadConfig(mirageConfig); ` in the beforeEach hook.

Does this should be done with `setupMirage()` ?

**Comment by samselikoff** [comment] 2018-10-13 15:57
hm, looks like the mirage config isn't being picked up by default. You should not have to do that manually. Where is your mirage config?

**Comment by GCorbel** [comment] 2018-10-13 17:11
My mirage config is under `mirage/config.js`, the default path.

**Comment by samselikoff** [comment] 2018-10-13 17:16
Seems weird. Any chance you could post a minimal reproduction?

**Comment by GCorbel** [comment] 2018-10-14 17:00
I will try to reproduce the issue with a new app but the app I'm working on isn't very complicated. I keep you up to date.

**Comment by samselikoff** [comment] 2018-11-19 22:31
I believe ember-mocha's README addresses this [here](https://github.com/emberjs/ember-mocha#setup-tests). I think you need to do something like this:

```js
const hooks = setupApplicationTest();
setupMirage(hooks);
```

Closing for now but please ping here if you're still having trouble!

**Closed by samselikoff** 2018-11-19 22:31 UTC
Labels: Question

**Comment by kennydp** [comment] 2018-11-20 11:12
I have the same issue. I started using mocha in our project and the config can't be found when testing. It does load when I just serve with mirage enabled. I tried checking how this was done and the `resolveRegistration` function just returns undefined (for either `base-config` or `test-config`)

I have used the steps that are in the ember-mocha's readme, but this did not seem to load the config.
Our setup may be a bit more complex, but I'll try to see if I can reproduce it in a new app and try to get back to you this week.

**Comment by samselikoff** [comment] 2018-11-20 11:31
@kennydp Sounds good, please report back here and we can just reopen the issue 👍

**Comment by kennydp** [comment] 2018-11-23 09:30
Looks like it was a config issue. I had the test-helper setup up in the wrong way. When I changed it as instructed in the [ember-mocha README](https://github.com/emberjs/ember-mocha#setting-the-application), it worked correctly.
