### ISSUE TITLE
this.get() urls need to be preceded with a "/" when this.namespace is not being used

### ISSUE THREAD

**Issue by notmessenger** [samselikoff/ember-cli-mirage#86] opened 2015-04-08 14:21 UTC
When `this.namespace` is not set in `config.js` you have to define the url used for `this.get()` with a "/" preceding the values (i.e. `this.get('/api/resource')`) but not for calls to `this.put()`, `this.post()`, or `this.del()`.

If you set `this.namespace` then all of these function "out of the box" without any errors about incorrect urls.

**Comment by samselikoff** [comment] 2015-04-21 23:57
Hm that's annoying. A default namespace of `/` should take care of this?

**Comment by blimmer** [comment] 2015-08-15 22:51
I can't reproduce this issue. I [posted an example](https://github.com/blimmer/ember-cli-example-app-for-github/compare/ember-cli-mirage-issue-86) here. I'm going to close this, but if you're still experiencing this problem, please reopen with an example (feel free to fork my example linked above!)

**Closed by blimmer** 2015-08-15 22:51 UTC
Labels: bug
