### ISSUE TITLE
Pull in a .bind polyfill for PhantomJS

### ISSUE THREAD

**Issue by brancusi** [samselikoff/ember-cli-mirage#216] opened 2015-07-27 19:49 UTC
Hi,

Getting a strange error on acceptance tests only in phantomjs. All works fine in chrome. Here are the steps to reproduce:

Using ember-cli: version: 1.13.1

```bash

$ ember init
$ ember g acceptance-test something

```

Update the test and force a simple assert:

```javascript
test('visiting /something', function(assert) {
  assert.ok(true);
});
```

Run the test

```bash
$ ember test
```
Notice everything passes

```bash
$ ember install ember-cli-mirage 
$ ember test --server
```

Phantomjs fails now but chrome is ok.

Am I missing some config or helper? I looked through all the docs but could not find any special setup.

Thanks

**Comment by samselikoff** [comment] 2015-07-27 23:23
Hmm I wasn't able to reproduce. Node version?

**Comment by brancusi** [comment] 2015-07-28 03:50
Strange:

ember -v outputs:

```
version: 1.13.1
node: 2.2.1
npm: 2.12.1
```

Thanks

**Comment by samselikoff** [comment] 2015-07-28 12:59
node 2.2.1? is that iojs or something?

**Comment by brancusi** [comment] 2015-07-28 14:44
Yes, good point I will try with node. Strange that it would work without mirage though and also with chrome.

The actual error message is:

```
Acceptance: Something: first test
    ✘ beforeEach failed on first test: 'undefined' is not a function (evaluating 'extend['default'].bind(Model, null)')
        
    ✘ afterEach failed on first test: 'undefined' is not an object (evaluating 'target[method]')
```

```javascript
import { module, test } from 'qunit';
import startApp from 'testproject1/tests/helpers/start-app';

var application;

module('Acceptance: Something', {
  beforeEach: function() {
    application = startApp();
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
  }
});

test('first test', function(assert) {
  assert.ok(true);
});
```

Does that shed any light on the issue? Will report back.

**Comment by samselikoff** [comment] 2015-07-28 14:45
Ahh yes it does, it's that Phantom doesn't support `.bind`. You can pull [this](https://github.com/kdimatteo/bind-polyfill) in for now

**Comment by mattmcmanus** [comment] 2015-07-28 15:08
The polyfil is only needed for PhantomJS 1.9. Bind is present in 2.0. Unfortunately circlecii comes with 1.9 installed.

**Comment by brancusi** [comment] 2015-07-28 15:41
Nice, thank you guys! I was indeed running phantom 1.9, all good once upgraded to 2.

**Comment by samselikoff** [comment] 2015-07-28 17:24
great! I'll keep this open bc there's no reason we shouldn't just include it, so others don't run into this

**Comment by jherdman** [comment] 2015-07-28 19:53
Something to consider is that you're most certainly experiencing this error with or without Mirage. It's probably wise to leave it up to the implementor of the Ember project to patch Function themselves, either via Babel's polyfill or similar. There no real reason to have this project patch Function considering it may not be needed anyways.

**Comment by samselikoff** [comment] 2015-07-28 20:59
Good point, maybe we should just add a note about this in the docs

**Comment by blimmer** [comment] 2015-08-14 13:28
I think we can close this because of [this commit](https://github.com/samselikoff/ember-cli-mirage/commit/928abc5d4c43a641ff64264cea71764f1fe25bc1).

**Comment by samselikoff** [comment] 2015-08-14 13:42
:+1:

**Closed by samselikoff** 2015-08-14 13:42 UTC
