### ISSUE TITLE
Error: Request was formatted incorrectly.

### ISSUE THREAD

**Issue by ctataryn** [samselikoff/ember-cli-mirage#1047] opened 2017-03-18 18:04 UTC
Sorry folks, I couldn't quite get twiddle to reproduce my error properly.  Essentially what I'm doing is using `ember-simple-auth` to facilitate an AJAX call to my back-end to simulate a login request that Mirage will fake out.

In the scenario where the user enters an incorrect username/password, I have Mirage kicking back a 400 `Response` like so:

```javascript
  this.post('/api/auth', (schema, request) => {
     if (...) {
      return {
        ...
        }
      };
    } else {
      return new Response(400, {'Content-Type': 'application/json'}, {error: 'Invalid login'});
    }
```

In the "good" scenario everything works fine, however in the case where the `else` statement kicks in I see the following error in my browser's console:

```
Request was formatted incorrectly.
Error
    at BadRequestError.AjaxError (http://localhost:4200/assets/vendor.js:126656:16)
    at BadRequestError (http://localhost:4200/assets/vendor.js:126709:15)
    at Class.handleResponse (http://localhost:4200/assets/vendor.js:127467:16)
    at Object.hash.error (http://localhost:4200/assets/vendor.js:127223:31)
    at fire (http://localhost:4200/assets/vendor.js:3627:31)
    at Object.fireWith [as rejectWith] (http://localhost:4200/assets/vendor.js:3757:7)
    at done (http://localhost:4200/assets/vendor.js:9566:14)
    at http://localhost:4200/assets/vendor.js:9806:9
    at FakeRequest.<anonymous> (http://localhost:4200/assets/vendor.js:71995:9)
    at FakeRequest.dispatchEvent (http://localhost:4200/assets/vendor.js:72039:24)
```

This is also causing my tests to fail and I was wondering how I could get a 400 response to work properly using Mirage?

P.S. my AJAX request looks like this:

```javascript
// app/authenticators/my-login.js

import Ember from 'ember';
import Base from 'ember-simple-auth/authenticators/base';

export default Base.extend({
  ajax: Ember.inject.service('ajax'),

  authenticate(email, password) {
    return this.get('ajax').request(
      '/api/auth', {
        method: 'POST',
        headers:  {'Content-Type': 'application/json'},
        data: JSON.stringify( { 'auth': { 'email': email, 'password': password } } )
      });
  },

});

```

**Comment by Aaronfischer** [comment] 2017-06-01 16:09
I'm also seeing this error as well. Not sure if this is related as it doesn't have to do with setting any kind of `else` within the route handler.

If I statically return the response in my acceptance tests (to test failures) in a few specific cases I get this error. I can't determine where the root cause is though.
```
server.delete('/lists/4/items',
    {
        errors: [
            {
                'status': '400',
                'title':  'Bad Request',
                'detail': 'Generic error removing contact from a list.'
            },
            {
                'title':  'Validation',
                'detail': 'Generic error with source.parameter',
                'source': {
                    'parameter': 'filter[contacts]',
                },
            },
        ]
    },
    400
);
```

**Comment by Aaronfischer** [comment] 2017-06-01 16:30
It looks like it(at least mine) may actual be an issue with ember-ajax, going from 2.5.X to 3.0.0 some error responses get wrapped in `payload:{ errors: [...] }` instead of the previous flatter `errors: [...]`
https://github.com/ember-cli/ember-ajax/releases/tag/v3.0.0

(not sure why it only effects a few of my response though and not all of them, I guess because I'm using ember-data 95% of the time and ajax for very specific requests)

**Comment by samselikoff** [comment] 2017-08-29 13:05
Sorry for the delay.

I tried to reproduce: https://github.com/samselikoff/ember-cli-mirage/issues/1047 Could you take a look?

**Comment by samselikoff** [comment] 2018-04-30 01:01
I apologize for not responding to this!

I'll go ahead and close this issue for now since it's quite old, but if you’re still having trouble, please ping me here or on slack @samselikoff and I will reopen + discuss.

**Closed by samselikoff** 2018-04-30 01:01 UTC
