### ISSUE TITLE
Mirage is not working with an addon

### ISSUE THREAD

**Issue by BryanHunt** [samselikoff/ember-cli-mirage#524] opened 2016-01-22 02:14 UTC
I'm trying to use Mirage 0.2.0-beta.3 inside an add-on with the dummy app.  The first problem I ran into is:

```
Attempting to watch missing directory: /Users/bhunt/Documents/Code/OpenSource/ember-d3/mirage
Error: Attempting to watch missing directory: /Users/bhunt/Documents/Code/OpenSource/ember-d3/mirage
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:90:11)
    at /Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:94:35
    at lib$rsvp$$internal$$tryCatch (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at /Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

If you work around this problem my creating an empty mirage directory at the project root, you then get:

`Uncaught Error: Could not find module dummy/mirage/config imported from dummy/initializers/ember-cli-mirage`

**Comment by samselikoff** [comment] 2016-01-27 13:53
Thanks for reporting, we'll get this situated before the 0.2.0 release.

**Comment by cibernox** [comment] 2016-01-31 15:04
I also found this issue today after update from 0.1.X.

The stack trace is very very similar:

```
Attempting to watch missing directory: /Users/miguelcamba/code/own/ember-power-select/mirage
Error: Attempting to watch missing directory: /Users/miguelcamba/code/own/ember-power-select/mirage
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/Users/miguelcamba/code/own/ember-power-select/node_modules/broccoli-sane-watcher/index.js:90:11)
    at /Users/miguelcamba/code/own/ember-power-select/node_modules/broccoli/lib/builder.js:94:35
    at lib$rsvp$$internal$$tryCatch (/Users/miguelcamba/code/own/ember-power-select/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/miguelcamba/code/own/ember-power-select/node_modules/rsvp/dist/rsvp.js:505:17)
    at /Users/miguelcamba/code/own/ember-power-select/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/Users/miguelcamba/code/own/ember-power-select/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)

```

**Comment by cibernox** [comment] 2016-01-31 22:15
Just to paste the solution I've found on the app side, even if this is addressed by ember-cli-mirage eventually.

Ensure that in the `ember-cli-build.js` you pass the proper folder to the mirage config.

```js
  var app = new EmberAddon(defaults, {
    'ember-cli-mirage': {
      directory: path.resolve(__dirname, path.join('tests', 'dummy', 'mirage'))
    }
  });
```

**Closed** 2016-02-02 12:09 UTC
Labels: bug, help wanted

**Comment by KeithYJohnson** [comment] 2016-02-07 15:37
Just upgraded to `"ember-cli-mirage": "0.2.0-beta.3",` nombom'd, and `ember serve` is throwing

```
version: 1.13.8

Livereload server on http://localhost:49152
Serving on http://localhost:4200/
Attempting to watch missing directory: /Users/keithjohnson/play/kwoter/tests/dummy/mirage
Error: Attempting to watch missing directory: /Users/keithjohnson/play/kwoter/tests/dummy/mirage
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/Users/keithjohnson/play/kwoter/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:90:11)
    at /Users/keithjohnson/play/kwoter/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:86:35
    at lib$rsvp$$internal$$tryCatch (/Users/2keithjohnson/play/kwoter/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/keithjohnson/play/kwoter/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/keithjohnson/play/kwoter/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/keithjohnson/play/kwoter/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

hey @samselikoff anything I'm doing wrong here?  Thanks!

**Comment by cibernox** [comment] 2016-02-07 17:15
@KeithYJohnson I fixed that but it is only in master, 0.2.0-beta.3 is older.

**Comment by samselikoff** [comment] 2016-02-09 04:57
Just published beta-4, give it a shot and let me know if you run into any problems.

**Comment by KeithYJohnson** [comment] 2016-02-09 13:18
great thanks!

**Comment by masterchef** [comment] 2019-03-27 16:28
It took me some time to figure this error out, it would be great to document this behavior in official docs.

**Comment by samselikoff** [comment] 2019-03-27 23:47
@masterchef document what? you shouldn't have to do anything to use Mirage in an addon since #543

**Comment by masterchef** [comment] 2019-03-27 23:56
@samselikoff, I'm on the latest version and if I don't specify
```
ENV['ember-cli-mirage'] = {
    directory: 'mirage'
}
```
I get the error below when running `npm test` or `ember s`:
```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Directory not found: /Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/tests/dummy/mirage
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Directory not found: /Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/tests/dummy/mirage
  - name: BuilderError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: BuilderError: Directory not found: /Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/tests/dummy/mirage
    at Builder.checkInputPathsExist (/Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:268:15)
    at new Builder (/Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:66:10)
    at Builder.setupBroccoliBuilder (/Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/node_modules/ember-cli/lib/models/builder.js:85:24)
    at new Builder (/Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/node_modules/ember-cli/lib/models/builder.js:32:10)
    at BuildTask.run (/Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/vtruchan/development/test-analysis-frontend/test-analysis-frontend-fe/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

=================================================================================
```

**Comment by samselikoff** [comment] 2019-03-28 00:02
definitely seems like a bug. Will have to look into it.

**Comment by samselikoff** [comment] 2019-03-28 00:03
@masterchef Could you open a new issue with a simplified reproduction?

**Comment by samselikoff** [comment] 2019-03-28 00:03
@masterchef Could you open a new issue with a simplified reproduction?

**Comment by masterchef** [comment] 2019-03-28 00:17
Opened: https://github.com/samselikoff/ember-cli-mirage/issues/1564
