### ISSUE TITLE
Disable mirage for certain tests

### ISSUE THREAD

**Issue by matthias-k** [samselikoff/ember-cli-mirage#1058] opened 2017-03-27 16:19 UTC
Hi,

we are using ember mirage to mock API response for our tests. However, we now want to add end2end tests which run on an actual API. For this I need to disable mirage in some (acceptance)-tests, but I have not yet managed to do so. Is there any mechanism to disable mirage for certain tests?

Here is a Twiddle showcasing what I want to accomplish:
https://ember-twiddle.com/16ae50cc7cdb8019d67418586442d4d9?openFiles=tests.acceptance.my-acceptance-test.js%2C

Best,
  Matthias

**Comment by NLincoln** [comment] 2017-03-27 16:43
One of the reasons I can see your tests failing is that you're making a jquery ajax call to some url, and then relying on `andThen` to wait for async behavior. The problem is that `andThen` only waits for async events within the runloop, and jquery isn't runloop-aware. You'll need to use a runloop-aware method of getting ajax calls, or simply put the assert condition within the callback of the jquery ajax call. Something like this: (?)

```js
return $.ajax({ opts }).then((response) => assert.ok(response))
```
You can verify this is happening for yourself by placing an `assert.ok(false)` in the jquery callback and seeing that it never runs.

**Comment by matthias-k** [comment] 2017-03-27 18:13
Thanks for the quick answer. Would it be enough to use `Ember.RSVP.cast` to make the ajax call a proper ember promise? I did so and added an assert statement into the `then`-path but Mirage still complains about not being able to resolve the URL I'm querying (which is not surprising since I haven't figured out how to disable mirage for this test):
```
Mirage: Your Ember app tried to GET 'https://jsonplaceholder.typicode.com/posts/1',
         but there was no route defined to handle this request.
         Define a route that matches this path in your
         mirage/config.js file. Did you forget to add your namespace?
MirageError @ addon.js:54484
...
```

**Comment by NLincoln** [comment] 2017-03-27 19:33
You need to make the mirage config's `urlPrefix` `https://jsonplaceholder.typicode.com`, since that's the root url you're querying. Right now mirage is only handling requests from 'ember-twiddle.com'

**Comment by NLincoln** [comment] 2017-03-27 19:36
The other problem I see is that you're requesting the url `/posts/1`, but your mirage config only has handlers for `/user`

**Comment by matthias-k** [comment] 2017-03-28 09:08
Maybe I was unprecise in my original post: My intention is _not_ to use mirage for handling API requests in this test (but in some others, therefore I can't just disable it alltogether). Therefore adding handlers to mirage for these urls won't solve the problem -- in fact in my own use case I even have mirage handlers registered for some of the urls I want to access. The problem is keeping mirage from handling requests in this specific test. Is there any way to do so?

**Comment by samselikoff** [comment] 2017-03-28 19:16
@matthias-k you could try calling `this.passthrough()` at the beginning of tests you want Mirage to ignore. Or you could hook into the initializer. I would write a testHelper for either `enableMirage()` or `disableMirage()` so it's easy to use

**Comment by matthias-k** [comment] 2017-03-28 21:07
@samselikoff using `passthrough` was one of my first ideas, too. However, in an acceptance tests, `this.passthrough` is not a function and neither `server` nor `this.server` (the first one should be available according to the [documentation](http://www.ember-cli-mirage.com/docs/v0.3.x/acceptance-testing/) ) are defined either. I added all (failing) versions to the [twiddle](https://ember-twiddle.com/16ae50cc7cdb8019d67418586442d4d9?openFiles=tests.acceptance.my-acceptance-test.js%2C). Am I missing something?

**Comment by samselikoff** [comment] 2018-04-30 01:05
I apologize for not responding to this!

You should be able to call `server.shutdown()` if you ever want to force Mirage to shutdown.

I'll go ahead and close this issue for now since it's quite old, but if you’re still having trouble, please ping me here or on slack @samselikoff and I will reopen + discuss.

**Closed by samselikoff** 2018-04-30 01:05 UTC
