### ISSUE TITLE
Simulate a long network request for just one endpoint

### ISSUE THREAD

**Issue by Jordan4jc** [samselikoff/ember-cli-mirage#403] opened 2015-11-24 02:53 UTC
How would I go about doing this in mirage? I tried setting the return value in a setTimeout but I guess mirage is not resolving when I return something? I don't want to set the timing on everything just this one endpoint. What would that process look like?

**Comment by samselikoff** [comment] 2015-12-14 13:29
Currently, this is not supported, though this is a feature in the backlog.

Closing (duplicate of #55).

**Closed by samselikoff** 2015-12-14 13:29 UTC
