### ISSUE TITLE
Associations not working for hasMany

### ISSUE THREAD

**Issue by kcin1018** [samselikoff/ember-cli-mirage#980] opened 2017-01-09 21:00 UTC
Hello,
  I am trying to use this addon (version 0.3.0-beta.4) with my app and running into some problems with the hasMany association creations.  I have created a twiddle to show what is going on.

https://ember-twiddle.com/f1741d3d87f3b8e9052f664257cd178e

The error is saying that I haven't defined a relation but I believe that I have.  Removing the hasMany relation biosample from the metaproject model makes it work just fine so something is wrong with the hasMany.

**Comment by Azdaroth** [comment] 2017-01-09 22:51
Hey @kcin1018,

`biosample` is apparently a `hasMany` relationship, `association` helper is supposed to be used for `belongsTo` type relationships, maybe it should be clarified in the docs.

 I think in your case `afterCreate` hook would do the job. Hope it helps.

**Comment by samselikoff** [comment] 2017-01-10 02:30
@Azdaroth if true I think this should be fixed. `association` helper should introspect and invoke the factory for the named relation and set it up properly. What do you think?

**Comment by Azdaroth** [comment] 2017-01-10 07:40
@samselikoff I think we should make it more clear that it's intended to be used only for setting up `to-one` associations. In this case it's about `to-many` relationship, I'm not really sure what would be the expected behaviour in such case. E.g. if `user` had many `posts`, we could set up the following factory:

``` js
// mirage/factories/user.js

export default Factory.extend({
  posts: association()
});
```

But what's the expected result here? To create one instance of `post`? Multiple instances? If yes, how many? That would be a bit ambiguous, I think we should strictly add in the error message (when introspecting the model) that it's about `belongsTo` relationship and clarify it more in the docs. And suggest using `afterCreate` hook for setting up `hasMany` associations. Sounds fair?

**Comment by kcin1018** [comment] 2017-01-10 14:53
@Azdaroth thanks for the tips.  I didn't realize it was for belongsTo type relations only.  I'll try the afterCreate hooks.

**Comment by Azdaroth** [comment] 2017-01-10 17:01
@samselikoff Throw for `hasMany` or maybe keeping it like it is now, but adding in the error message that it is about `belongsTo` association? That way with one error message we got both `hasMany` relationships and missing `belongsTo` relationship  covered.

**Comment by samselikoff** [comment] 2017-01-10 17:16
Ah yep. Perfect.

**Comment by Azdaroth** [comment] 2017-01-11 14:59
Ok, submitted a PR for that: https://github.com/samselikoff/ember-cli-mirage/pull/981

**Comment by samselikoff** [comment] 2017-04-14 13:33
#981 closes

**Closed** 2017-04-14 13:33 UTC
