### ISSUE TITLE
mirage is not aware of uncountable models (inflector configs)

### ISSUE THREAD

**Issue by givanse** [samselikoff/ember-cli-mirage#265] opened 2015-09-02 18:51 UTC
I'm using an addon that makes a few non-REST API calls, for that purpose I have an initializer where I use the inflector to mark a model as 'uncountable'.

The flow in my app is:
- configure the inflector `inflector.uncountable('paypal')` (inside an initializer)
- use the adapter to build a URL `adapter.buildUrl('paypal')`
- a request to `localhost:3000/api/paypal` is done

When I add mirage, it intercepts the requests and looks for the following URL: `localhost:3000/api/paypals`

Mirage wasn't aware of the inflector config (?)

**Comment by samselikoff** [comment] 2015-09-02 19:42
can I see your `mirage/config.js`?

**Comment by givanse** [comment] 2015-09-02 19:53
Sure, this is it:

```
export default function() {

  /* post */

  this.get('/api/v1/posts', function(db/*, request*/) {
    return {posts: db.posts};
  });

  this.get('/api/v1/posts/:id', function(db, request) {
    var id = request.params.id;

    return {posts: db.posts.find(id)};
  });

  /* post-category */
 
  this.get('/api/v1/postCategories', function(db/*, request*/) {
    return {postCategories: db['post-categories']};
  });

  this.get('/api/v1/postCategories/:id', function(db, request) {
    var id = request.params.id;

    return {postCategories: db['post-categories'].find(id)};
  });

  /* event */

  this.get('/api/v1/events', function(db/*, request*/) {
    return {events: db.events};
  });

  this.get('/api/v1/events/:id', function(db, request) {
    var id = request.params.id;

    return {events: db.events.find(id)};
  });

  /* album */

  this.get('/api/v1/albums', function(db/*, request*/) {
    return {albums: db.albums};
  });

  this.get('/api/v1/albums/:id', function(db, request) {
    var id = request.params.id;

    return {albums: db.albums.find(id)};
  });

  /* skip spree routes */

  // TODO:
  // https://github.com/samselikoff/ember-cli-mirage/pull/188
  // https://github.com/samselikoff/ember-cli-mirage/pull/134
  this.pretender.get('http://localhost:3000/api/ams/countries', this.pretender.passthrough);
  this.pretender.get('http://localhost:3000/api/ams/products', this.pretender.passthrough);
  this.pretender.get('http://localhost:3000/api/ams/products/:slug', this.pretender.passthrough);
  this.pretender.get('http://localhost:3000/api/ams/taxonomies', this.pretender.passthrough);
  this.pretender.get('http://localhost:3000/api/ams/orders/:id', this.pretender.passthrough);
  this.pretender.post('http://localhost:3000/api/ams/orders', this.pretender.passthrough);
  this.pretender.post('http://localhost:3000/api/ams/line_items', this.pretender.passthrough);
  this.pretender.put('http://localhost:3000/api/ams/checkouts/:id', this.pretender.passthrough);

  //TODO: https://github.com/samselikoff/ember-cli-mirage/issues/265
  //this.pretender.post('http://localhost:3000/api/ams/paypal', this.pretender.passthrough);
}

/*
You can optionally export a config that is only loaded during tests
export function testConfig() {

}
*/
```

**Comment by Arkham** [comment] 2015-09-21 17:51
Hey @givanse, I had the same problem and the steps I did to fix it are:

* Create an ad-hoc adapter where you specify the `pathForType`
```js
import ApplicationAdapter from './application';

export default ApplicationAdapter.extend({
  pathForType: function() {
    return 'paypal';
  }
});
```
* Configure the inflector initializer to start before ember-cli-mirage
```js
import Ember from 'ember';

export default {
  name: 'inflector',

  before: 'ember-cli-mirage',

  initialize: function() {
    var inflector = Ember.Inflector.inflector;
    inflector.uncountable('paypal');
  }
};
```

Hope this helps :)

**Comment by ballPointPenguin** [comment] 2015-10-13 03:00
thanks, @Arkham that helped me with a similar issue

**Comment by ynx** [comment] 2016-02-16 21:24
Thanks @Arkham I solved a similar problem using your approach.

**Comment by backspace** [comment] 2016-07-11 21:15
Another thanks to @Arkham. Note that I needed to [add a conditional](https://github.com/travis-ci/travis-web/blob/ba9c5720e09480be5b1f3d9d5809a1681206ffff/app/initializers/configure-inflector.js) so `before` wouldn’t be set in production, because in that application, Mirage isn’t present in production, and therefore the site wouldn’t launch.

**Comment by samselikoff** [comment] 2016-07-16 07:42
I'm glad you all figured out a short-term fix, sorry this hasn't been fixed (it's come up for quite a few folks).

This thread may have some useful information on getting a proper fix landed: https://github.com/samselikoff/ember-cli-mirage/issues/793

**Comment by samselikoff** [comment] 2017-01-20 21:25
Trying to cleanup issues, closing as duplicate of https://github.com/samselikoff/ember-cli-mirage/issues/313

**Closed by samselikoff** 2017-01-20 21:25 UTC
Labels: icebox
