### ISSUE TITLE
Serializer does not return nested includes when specified in request

### ISSUE THREAD

**Issue by christophermlne** [samselikoff/ember-cli-mirage#1299] opened 2018-04-16 13:29 UTC
In the following example, `user.memberships` will result in a `Settings` record containing an included `User` record but the `User` record will not include `Memberships`.

I'm wondering is this a bug or expected behaviour? I know I could hack around this in the serializer but want to avoid if Mirage is actually capable of this and I'm doing something wrong.

```js
model() {
  return get(this, 'store')
      .queryRecord('settings', { 
         filter: { id: 'me' },
         include: 'membership,user,user.memberships,organization' 
      })
}
```

**Comment by chrisgame** [comment] 2018-04-24 12:11
I have the same problem. Everything works fine when i request a relationship on the resource i'm requesting but when i request a relationship of the relationship, using the `include: 'relationship1.relationship2'` syntax, relationship2 is not returned.

**Comment by chrisgame** [comment] 2018-05-01 11:09
Here is an example twiddle with the problem https://ember-twiddle.com/dc40955ade48b2b90a6b59c1f5d35c6c?openFiles=mirage.scenarios.default.js%2C

Although I am requesting an include of `eons.eras` only eons are returned in the include. Upon inspection it looks like the relationship is built correctly.
![image](https://user-images.githubusercontent.com/766429/39470297-ba5db170-4d34-11e8-90aa-1721372099da.png)

In the example above i'm using the standard JSONAPISerialiser. Even if I add a serializer for each model and specify an include and/or set `alwaysIncludeLinkageData: true` it produces the same result as above.

**Comment by samselikoff** [comment] 2018-05-01 15:27
This does sound like a bug as the expected behavior would be for all relationships to be included

**Comment by samselikoff** [comment] 2018-05-01 15:31
@chrisgame The twiddle is actually incorrect:

```
GET /supereons?include=eons.eras
```

This is invalid because an `eon` model doesn't have an `eras` relationship, it has an `era` relationship.

If you (1) change that, and (2) define the `era` model in Ember Data it should work.

Also, did you know you don't need to define Mirage models explicitly anymore? If you add your relationships to your Ember Data models they will be used automatically by Mirage.

**Comment by samselikoff** [comment] 2018-05-01 15:33
@christophermlne I suspect something similar is going on for you... could you reproduce in a twiddle?

Also,

```
include: 'membership,user,user.memberships,organization' 
```

With json:api you can just change this to 

```
include: 'membership,user.memberships,organization' 
```

(i.e. you can drop the standalone `user` since you have it already at `user.memberships`.)

**Comment by samselikoff** [comment] 2018-05-01 15:34
Closing because this is a question and I only want to keep bugs open, but let's continue to discuss here :)

**Closed** 2018-05-01 15:33 UTC
Labels: Question

**Comment by chrisgame** [comment] 2018-05-04 10:07
@samselikoff Thanks so much for finding the problem! The lack of an ember data model for era was deliberate, I was just trying to get to the point where mirage produced a payload with `eras` and forced that error from ember. I had totally missed that I had defined a `hasMany` relationship with a singular instead of plural though 🤦‍♂️ .
I didn't know the mirage models are no longer required, thats a really nice step.

**Comment by samselikoff** [comment] 2018-05-05 23:37
Understood - glad you figured it all out!
