### ISSUE TITLE
Can't import things from tests directory

### ISSUE THREAD

**Issue by allthesignals** [samselikoff/ember-cli-mirage#1445] opened 2018-12-19 16:29 UTC
I'm attempting to import a test helper that lives in tests/helpers:

`import random from 'labs-applicant-maps/tests/helpers/random-geometry';`

...from a mirage factory living at mirage/factories/project.

But, it throws this error in the console!

`Uncaught Error: Could not find module `labs-applicant-maps/tests/helpers/random-geometry` imported from `labs-applicant-maps/mirage/factories/project``

I've tried using relative paths as well. What am I doing wrong? I'm currently using: 

```
    "ember-auto-import": "1.2.19",
    "ember-cli-mirage": "0.4.10",
```

**Comment by allthesignals** [comment] 2018-12-19 16:47
I've had to copy the file into the mirage directory just to get this to import. Anyone know what is happening with the resolver here?

**Comment by samselikoff** [comment] 2018-12-21 05:41
Sorry you're running into this!

Any chance you could post a simplified reproduction, either on a GitHub repo or by forking the [CodeSandbox](https://codesandbox.io/s/003o6pq34n)?

**Comment by allthesignals** [comment] 2018-12-31 19:37
It may have something to do with this issue: https://github.com/ember-decorators/argument/issues/93

**Comment by erichonkanen** [comment] 2019-02-10 05:59
getting same thing on 4.9 and upgraded to 4.14 same thing.
```
import { AWSIotStub } from 'client-web/tests/helpers/base';
```
```loader.js:247 Uncaught Error: Could not find module `client-web/tests/helpers/base` imported from `client-web/mirage/config````

**Comment by samselikoff** [comment] 2019-02-20 21:52
Unable to reproduce, I tried it in `test-projects/01-basic-app` and everything worked

```
// mirage/config.js

import mirageHelper from 'basic-app/tests/helpers/my-mirage-helper';
console.log(mirageHelper);
```

Also tried it in the factory.

If y'all are still running into this, could you try to provide a simplified reproduction?

**Comment by makepanic** [comment] 2019-02-21 11:58
I'm seeing the same behavior when running the app in `development` environment.
It looks like everything works as expected in `test` mode.

I guess during development, the test tree isn't merged which causes the resolver not being able to find the module.

**Comment by allthesignals** [comment] 2019-02-21 12:49
@makepanic yes, let me reproduce, it's been a while. Will have something later today.

**Comment by allthesignals** [comment] 2019-02-21 16:10
Here's a branch of my issue: https://github.com/NYCPlanning/labs-applicantmaps/tree/import-issue

Here's where the import fails: https://github.com/NYCPlanning/labs-applicantmaps/blob/import-issue/mirage/factories/geometric-property.js#L2

Here's the file I'm attempting to import: https://github.com/NYCPlanning/labs-applicantmaps/blob/import-issue/tests/helpers/random-geometry.js

I've also tried relative paths. You should be able to clone and run this project to see the error in the console. 

Thanks all!

**Comment by makepanic** [comment] 2019-02-21 16:26
How did you trigger the error? Did you it happen when running your tests or during regular app usage?

**Comment by allthesignals** [comment] 2019-02-21 16:28
`ember s` triggers the error

**Comment by allthesignals** [comment] 2019-02-21 16:31
`ember test` does _not_ trigger the error

**Comment by makepanic** [comment] 2019-02-21 18:18
Thanks to help from @bendemboski , we found the cause:

When running the app directly, the browser opens `index.html` which isn't loading `tests.js`.
This file contains everything related to tests.

If you open `tests/index.html`, that will also load `tests.js` and add any modules under `tests/*` to the loader registry. 

This means without the tests file loaded, you can't import anything from `tests/*`.

With you moving the helpers to `/mirage`, they gets registered in both `index.html` and `tests/index.html`.

**Comment by samselikoff** [comment] 2019-02-21 18:19
I think this is actually not a Mirage issue - the `treeForTest` (in Broccoli terms) is not available to the app outside of the test environment. You'll see this if you try to import the helper in your Application route.

I think the solution is to put shared things under `/mirage` (since those can be imported into `/tests`, and also `/app`).

**Comment by samselikoff** [comment] 2019-02-21 18:19
Yes – basically what @makepanic said!

**Comment by samselikoff** [comment] 2019-04-14 19:24
Closing for now but please comment if you're still having trouble.

**Closed by samselikoff** 2019-04-14 19:24 UTC
Labels: Bug report

**Comment by mockey-jockey** [comment] 2020-06-26 13:42
Am facing the same thing and tried @makepanic instructions still having the same issue @samselikoff can u pls help here pls

Uncaught Error: Could not find module `project-name/tests/helpers/push-mirage-into-store` imported from `project-name/mirage/factories/addon`

Initially got this error and tried @makepanic instructions

After that

Uncaught Error: Could not find module `@ember/test-helpers` imported from `project-name/mirage/helpers/push-mirage-into-store`

can you pls help here to resolve this.

**Comment by cah-briangantzler** [comment] 2020-06-26 20:24
I am curious why you would be using pushMirageToStore from a factory, given that its job is to create a record in the mirage store.

The main problem here is that this method needs to lookup both the store and the mirage server to push from one to the other. It does this by getting the context of the test and then using that to lookup the store and the server. This context is what is being imported from the test-helpers and only available with ember tests.

```js
import { getContext } from '@ember/test-helpers';

  let context = getContext();
  let store = context.owner.lookup('service:store');

  let resources = Object.keys(context.server.schema) ..... // server is derived from context

```

if you want to use pushMirageToStore outside of tests, you need to make a new version that you can pass the store and the server into that you can access. If you do not have access to the store and server, then that would be the next problem to tackle.


As a note. I have a modified version of the pushToStore that allows for you to pass a config so that you can specify which tables to push as well as provide a where.    


I quickly modified this to accept a store and server although did not fully test, but perhaps this would help. As noted, you cant put this in test/helpers or addon-test-helpers because again, only accessible from tests

NOTE: This was meant to be deployed within ec-mirage as a PR. You will have to remove the asserts because of where they are imported from and the params are backwards from ember assert so you cant just replace the import with the one from ember debug. Looks like some of the comments in the description need adjusted to take into account the new server and store arguments.  

Wanted to get this to you quickly, but if willing to wait a bit, wil do more work on it.

```js
import { run } from '@ember/runloop';
import assert from '../addon/assert';

let pushMirageRecordsIntoStore = function(store, server, resource, where) {
  let models = server.schema[resource].all();
  let modelName = models.modelName;
  if (typeof where === "object") {
    models = server.schema[resource].where(where);
  }

  if (models.length > 0) {
    let serializer = server.serializerOrRegistry.serializerFor(modelName);

    let originalAlwaysIncludeLinkageData = serializer.alwaysIncludeLinkageData;
    serializer.alwaysIncludeLinkageData = true;

    let json = serializer.serialize(models);

    serializer.alwaysIncludeLinkageData = originalAlwaysIncludeLinkageData;
    run(() => {
      let jsonObj = {};
      jsonObj[`${modelName}`] = json;
      store.pushPayload(jsonObj);
    });
  }

  return models;
}

/**
 * This utility pushes the mirage store into the ember store
 *
 * You may also call this utility with an array of resource names. ['accounts', 'accountTypes']. These must
 * be the resource names camelized.
 *
 * You may also call it with a hash. This hash will have the resource names as the keys and the values will either
 * be true (push all models for that resource) or a where hash that will be applied to the that resource.
 * {
 *   accounts: true,
 *   accountTypes: { state: 'OH' }
 * }
 *
 * @param server   The mirage server
 * @param store    the store you wish mirage to push to
 * @param config   undefined means push all resources
 *                 An array will push only the resources in the array
 *                 hash in the form of resource=value    Value may be true, all models, or a where hash
 */
let pushMirageIntoStore = function(server, store, config) {
  assert(store, "You must supply a store to pushMirageIntoStore");
  assert(server, "You must supply a mirage server to pushMirageIntoStore");

  let resources = Object.keys(server.schema)
    .filter(key => server.schema[key].all !== undefined); // Get the resources

  let where = {};

  if (config) {
    let includes;
    if (Array.isArray(config)) {
      includes = config;
    } else {
      includes = Object.keys(config);
      where = config;
    }

    resources = includes.filter(item => {
      let found = resources.includes(item);
      assert(found, `Model of type '${item}' does not exist for push mirage into store.`);
      return found;
    });
  }

  resources.forEach(resource => {
    pushMirageRecordsIntoStore(store, server, resource, where[resource]);
  });
}

export {
  pushMirageIntoStore,
  pushMirageRecordsIntoStore
}
```

I was going to make the non server/store version in a PR, but given the problems, perhaps I should also provide this one as well.

**Comment by allthesignals** [comment] 2020-11-19 19:01
Anyone find a workaround? I can't seem to import an `ember-simple-auth` helper... it seems that I _can_ import other `@ember`-namespaced stuff.

Here's a reproduction: https://github.com/NYCPlanning/labs-applicant-portal/tree/e-simple-auth-issue
