### ISSUE TITLE
Unable to retrieve a single record by ID using store.find

### ISSUE THREAD

**Issue by idijan** [samselikoff/ember-cli-mirage#87] opened 2015-04-09 15:35 UTC
We have mirage fixtures for user objects under `\app\mirage\fixtures\users.js`.
Example objects look like:

```javascript
    {   
		"id": "21874377",
		"FullName": "John Doe",
		"Followed": false,
		"Items": ["52514158", "51910482", "51724768", "25737984", "1827392", "2931759", "18533765", "292928222", "828282828", "60651627", "38599570", "26749790", "56031085", "145134"]
	}, {
		"id": "22054154",
		"FullName": "Jane Doe",
		"Followed": true,
		"Items": ["59031445", "28237261", "928785647", "827354674", "17355675", "3496585", "30372446", "30372445", "30372444", "30372443", "32158695", "55100084", "2489673"]
	}
```
    
In a route, doing 

```javascript
export default Ember.Route.extend({
  model: function () {
    return this.store.find("user", "21874377");
  }
});
```

fails when using shorthand `this.get('/users/:id');` in `\app\mirage\config.js`, or even doing a custom handler:

```javascript
this.get('/users/:id', function(db, request) {
    var userId = request.params.id;
    var user = db.users.find(userId.toString());
    return {
      user: user
    };
  });
```
  
Error message is:
*Assertion Failed: Expected an object as `data` in a call to `push` for emberapp@model:user: , but was undefined*
Debugging in JS console (breakpoint in function handler), I didn't manage to get db.users.find() to return anything other than undefined.

A workaround is using `var user = db.users.where({id: userId.toString()});` but I'm puzzled about what's happening in the shorthand and users.find variants.

**Comment by samselikoff** [comment] 2015-04-09 15:46
Both the shorthand and `db.find` try to coerce ids to ints, and this is likely what's happening.

The reason I did this originally was because people seemed used to typing ids in as ints in their fixture files, and I wanted everything to just work in that case, without having to do things like `db.find(+request.params.id)`.

I think your situation is the much more common one - in fact as @lukemelia mentions in #67 there's nothing fundamentally numeric about an id. So I think this should be the default, or, probably we shouldn't coerce ids at all.

For now you can use your workaround with `.where`, or, just change the ids in your fixtures to ints (instead of strings). Thanks for taking the time to write this up!

**Comment by idijan** [comment] 2015-04-09 15:56
Great, that explains it - replacing IDs with ints indeed enables shorthand usage.
Thanks for the quick reply!

**Comment by samselikoff** [comment] 2015-04-09 15:59
np :)

closing in favor of #67

**Closed by samselikoff** 2015-04-09 15:59 UTC

**Comment by elskwid** [comment] 2015-04-30 16:45
@idijan I was having this issue as well and found another method which helped me avoid the confusion of fixtures/factories with integer ids and an API with string (UUID) ids:

```js
import Mirage from 'ember-cli-mirage';

export default Mirage.Factory.extend({
  id: (i) => 'user-factory-' + i,
  // other stuff ... 
});
```

This does what you'd expect (kudos @samselikoff!) and now I have string ids everywhere.

**Comment by heshamelmasry77** [comment] 2020-04-21 21:32
this is not working with me at all

**Comment by samselikoff** [comment] 2020-04-21 22:21
@heshamelmasry77 This issue is 5 years old 🙂 Best bet to get help is to open a new issue with a reproduction.
