### ISSUE TITLE
Records do not get updated if the parent is not changed

### ISSUE THREAD

**Issue by mupkoo** [samselikoff/ember-cli-mirage#1207] opened 2017-11-02 08:11 UTC
I tried to dig deeper into this and it looks like if you try to update a record without changing the parent, it gets saved twice. This is what happens.

```javascript
let schema = new Schema(db, {
  author: Model.extend({
    posts: hasMany()
  }),
  post: Model.extend({
    author: belongsTo()
  })
});

let author = schema.create('author');
let post = schema.create('post', { authorId: author.id });

post.update({ title: 'Updated title' });
```

Once you do this, `post.save` gets called for the first time. This triggers `author.save()`, which eventually triggers `post.save` again, but this time, the post has the old attributes, so re-updates with the old attributes, as `author.posts` contains clones of the `post` records.

**Comment by mupkoo** [comment] 2017-11-02 08:43
This commit is causing the problem -> https://github.com/samselikoff/ember-cli-mirage/commit/85a6ac052f38ffd80f41b6d8e87332a680d33740

**Comment by mupkoo** [comment] 2017-11-04 22:28
I tried to dig deeper into this and it looks like if you try to update a record without changing the parent, it gets saved twice. This is what happens.

```javascript
let schema = new Schema(db, {
  author: Model.extend({
    posts: hasMany()
  }),
  post: Model.extend({
    author: belongsTo()
  })
});

let author = schema.create('author');
let post = schema.create('post', { authorId: author.id });

post.update({ title: 'Updated title' });
```

Once you do this, `post.save` gets called for the first time. This triggers `author.save()`, which eventually triggers `post.save` again, but this time, the post has the old attributes, so the updates does not happen.

**Comment by mupkoo** [comment] 2017-11-04 22:32
If I remove the check introduced by https://github.com/samselikoff/ember-cli-mirage/commit/85a6ac052f38ffd80f41b6d8e87332a680d33740, only a single `save` is called, and it is the `post.save`.

**Comment by demsullivan** [comment] 2017-11-19 16:01
I'm seeing this too, but it's not 100% of the time. Instead of updating title, I'm updating the relationship, e.g.:

```
let schema = new Schema(db, {
  author: Model.extend({
    posts: hasMany()
  }),
  post: Model.extend({
    author: belongsTo()
  })
});

let author = schema.create('author');
let secondAuthor = schema.create('author');
let post = schema.create('post', { authorId: author.id });

post.update({ authorId: secondAuthor.id });
```

I've traced it to https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/model.js#L91-L95

Interestingly, at line 93, `this.attrs.authorId` === `attrs.authorId` as it should, but on line 95, *after* `this.save()`, that is no longer true and `this.attrs.authorId` is reverted back.

**Comment by mupkoo** [comment] 2017-11-19 17:01
I think it is because the author has an outdated reference of the posts. So we you update the post, it triggers `save` for the author, which triggers `save` for every single of the posts, but they are outdated.

@demsullivan have you tried this branch? It should fix the problem.

**Comment by demsullivan** [comment] 2017-11-19 17:24
Yeah that's my understanding... the weird thing is that it's intermittent. It works sometimes, but not other times. Like there's a race condition somewhere.

I haven't tried the fix, but I will try that shortly, thanks!

**Comment by demsullivan** [comment] 2017-11-25 14:58
Tested with #1208 - unable to reproduce the issue now, so it looks like it's fixed!

**Comment by samselikoff** [comment] 2018-05-06 03:47
I lost track of all the threads, but I believe this bug has been fixed.

I'll close this for now – feel free to ping me and I can reopen if anyone's still having trouble! 😄

**Closed by samselikoff** 2018-05-06 03:47 UTC
