### ISSUE TITLE
Ember Guides

### ISSUE THREAD

**Issue by collegeimprovements** [samselikoff/ember-cli-mirage#422] opened 2015-12-09 18:12 UTC
While following `ember-guides (2.2.0)` I copied the following code to `app/mirage/config.js` file.
```js
export default function() {
  this.get('/rentals', function() {
    return {
      data: [{
        type: "rentals",
        id: 1,
        attributes: {
          title: "Grand Old Mansion",
          owner: "Veruca Salt",
          city: "San Francisco",
          type: "Estate",
          bedrooms: 15,
          image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Crane_estate_(5).jpg"
        }
      }, {
        type: "rentals",
        id: 2,
        attributes: {
          title: "Urban Living",
          owner: "Mike Teavee",
          city: "Seattle",
          type: "Condo",
          bedrooms: 1,
          image: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Alfonso_13_Highrise_Tegucigalpa.jpg"
        }
      }, {
        type: "rentals",
        id: 3,
        attributes: {
          title: "Downtown Charm",
          owner: "Violet Beauregarde",
          city: "Portland",
          type: "Apartment",
          bedrooms: 3,
          image: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Wheeldon_Apartment_Building_-_Portland_Oregon.jpg"
        }
      }]
    }
  });
}
```

But it gives `Uncaught UnrecognizedURLError: /rentals` error. What can be done here? I'm stuck and not able to follow along with the guides. Please help.

**Comment by samselikoff** [comment] 2015-12-09 18:28
Hm, I just checked on my end and I can't reproduce. What version of Ember + Ember Data are you on?

**Comment by collegeimprovements** [comment] 2015-12-10 04:14
I'm using Ember Data 1.13.15 and Ember 1.13.10.
```ruby
DEBUG: -------------------------------
vendor.js:15996 DEBUG: Ember      : 1.13.10
vendor.js:15996 DEBUG: Ember Data : 1.13.15
vendor.js:15996 DEBUG: jQuery     : 1.11.3
vendor.js:15996 
DEBUG: -------------------------------
```

**Comment by samselikoff** [comment] 2015-12-10 12:48
Hm, ok. Can you post the entire console error, maybe a screenshot of what happens?

**Comment by collegeimprovements** [comment] 2015-12-10 14:32
Here it is: <img width="1440" alt="screen shot 2015-12-10 at 8 01 35 pm" src="https://cloud.githubusercontent.com/assets/1519705/11717846/ebed8614-9f78-11e5-9811-7e2072ae55f3.png">

**Comment by samselikoff** [comment] 2015-12-10 15:28
Can I see the trace (click the arrow)? I don't think that's a Mirage error, I think it's an Ember error. Are you trying to visit `/rentals` in your URL address bar? That won't work with Mirage.

**Comment by collegeimprovements** [comment] 2015-12-10 17:38
<img width="1439" alt="screen shot 2015-12-10 at 11 03 01 pm" src="https://cloud.githubusercontent.com/assets/1519705/11723048/39f2ca68-9f92-11e5-84fb-2d9eb505f0c0.png">

Yes. I'm trying to access `localhost:4200/rentals`. Because that's what they have advised in [ember-guides](http://guides.emberjs.com/v2.2.0/tutorial/ember-data/).

<img width="802" alt="screen shot 2015-12-10 at 11 06 39 pm" src="https://cloud.githubusercontent.com/assets/1519705/11723149/c2d08b18-9f92-11e5-9310-b9cfc334d67b.png">

**Comment by samselikoff** [comment] 2015-12-10 21:08
Right. Ember Data is making an AJAX request to `/rentals`, but you don't do that yourself.

Try putting the `this.store.findAll('rental')` code in your index route's `model()` hook. Then, when you visit the index route, you should see the request go through + respond in your console.

**Comment by samselikoff** [comment] 2015-12-10 21:09
I'm going to close this because this is not a Mirage bug, but feel free to keep asking questions here, if it still doesn't make sense.

**Closed by samselikoff** 2015-12-10 21:09 UTC

**Comment by fighterleslie** [comment] 2015-12-18 10:36
@collegeimprovements  I ran into the same problem when following the Ember official guide. Did you solve it?

**Comment by collegeimprovements** [comment] 2015-12-19 05:21
Unfortunately I'm still struggling. I'll try again today and update here if I can figure out the solution. Please do the same if you find out the solution.

**Comment by fighterleslie** [comment] 2015-12-19 13:32
@collegeimprovements FYI, I solved the problem today. I suggest you update Ember to 2.2.0 and Ember Data to Ember 2.2.1. As per your environment, you use Ember 1.13.10 and Ember Data 1.13.15 but you're following a guide of Ember 2.2.0. I think this my result in some inconsistencies. I suggest you install the ember-cli v2.2.0-beta.1 and use it to create Ember project (try `npm install -g ember-cli@2.2.0-beta.1`). 

The default serializer and adapter in Ember Data 1.x are DS.RESTSerializer and DS.RESTAdapter, respectively. In Ember Data 2.2.1, the dedault couterparts are DS.JSONAPISerializer and DS.JSONAPIAdapter. This may affect the AJAX request.

**Comment by samselikoff** [comment] 2015-12-20 13:08
@collegeimprovements I'm happy to pair with you, if you'd like. Would probably be easier to talk through this. Hit me up on slack or email (sam.selikoff[at]gmail.com).

**Comment by collegeimprovements** [comment] 2015-12-20 18:11
Hello  @fighterleslie, Bingo. It works after I upgrade to `ember-cli 2.2.0-beta.1`
Thanks a lot. 
Sam thanks for the help. Can I ask you ember related questions here or on mail or on slack ?

**Comment by samselikoff** [comment] 2015-12-20 20:19
StackOverflow with the tag [ember-cli-mirage] is the best place, I get emailed about those. Or slack, or here.

**Comment by collegeimprovements** [comment] 2015-12-21 04:56
Thank you :)
