### ISSUE TITLE
Issue with mirage MODULE_UNIFICATION=true

### ISSUE THREAD

**Issue by chrisgame** [samselikoff/ember-cli-mirage#1294] opened 2018-04-02 22:55 UTC
Looks like something bad is happing when installing the mirage using ember-cli@3.1.0-beta.1 and `MODULE_UNIFICATION=true`. I have replicated the issue in isolation here https://github.com/chrisgame/mirage-modern-testing-issue/pull/1> Ignore the repo name i thought this was an issue with the new qunit version initially.

`this` within a non-rendering test (formally unit test) is over written with an empty object. If i follow the instructions for booting mirage, `server` is added to `this` but other than that the object is still empty.

I guess something is overwriting `this`, i couldn't see what though. Hopefully the attached example has all the detail needed to show the problem. The pr shows a passing test on travis prior to installation of mirage and then the fail.

**Comment by acorncom** [comment] 2018-04-03 12:34
@chrisgame it looks like the issue is probably related to the very first error you are getting re: config. Likely to be a conflict between mirage’s default folder setup and the new module unification resolver ...

**Comment by chrisgame** [comment] 2018-04-03 12:40
ah @acorncom, that would make total sense. Do you think in a unified module world the mirage folder still belongs in the root of the app?

**Comment by samselikoff** [comment] 2018-07-29 22:36
@chrisgame Thanks for taking the time to open the issue, and sorry about my delayed response!

I haven't formally tried MU yet, and am a little hesitant to invest time in it yet because it's still early and I know things are changing. Could you give me a tl;dr of your usage of it & your perceived stability of MU?

**Comment by chrisgame** [comment] 2018-08-20 14:32
Hi @samselikoff, no worries and apologies for my late response!

**Comment by samselikoff** [comment] 2019-04-14 19:25
I'm going to close this for now, as MU is still shaking out and looks to not even be an Octane feature.

We will definitely support the new file layout when it lands.

**Closed by samselikoff** 2019-04-14 19:25 UTC
Labels: Bug report
