### ISSUE TITLE
Currently impossible to use fastboot with mirage.

### ISSUE THREAD

**Issue by izelnakri** [samselikoff/ember-cli-mirage#1194] opened 2017-10-21 18:58 UTC
All ember mirage routes respond with 404 when I run mirage with ember fastboot via ```ember s --env=mirage```. 

I have custom ```mirage``` environment that runs mirage correctly in browser however ember-cli-mirage doesn't run properly with broccoli, during fastboot runtime. 

I hope we can merge express-mock server PR soon @samselikoff, I guess such feature would enable running mirage in node environment, and perhaps expose ```ember-cli-mirage``` package as a general frontend server mocking framework rather than a ember-only frontend mocking framework.

**Comment by Kuzirashi** [comment] 2017-11-06 14:37
I'm also looking to solution for this.

**Comment by izelnakri** [comment] 2017-11-06 16:08
@Kuzirashi check my memserver project. I'll release a superior ember mirage alternative in few months.

**Comment by rwwagner90** [comment] 2017-11-07 22:06
Just hit this issue as well. Spent a bunch of time debugging, trying to determine the cause, and turns out fastboot breaks mirage here. Anyone have a fix in mind?

**Comment by JackEllis** [comment] 2018-06-17 21:15
+1 for getting it to work with fastboot :)

**Comment by izelnakri** [comment] 2018-06-17 21:54
For the ones who want a mock server + ORM that works with fastboot: https://www.npmjs.com/package/ember-cli-memserver. Warning: not documented and different API, so its not mirage ;) memserver API is mostly stable & well tested, and I think much more intuitive.

**Comment by samselikoff** [comment] 2018-06-21 17:57
I'm going to close this for now as it's a feature request and [captured here](https://ember-cli-mirage.canny.io/admin/board/feature-requests/p/fastboot-support).

If there's anything that Mirage does that breaks a Fastboot build, we can reopen & fix as it's a bug. For now, Mirage just disables itself in Fastboot.

Fastboot support is a high priority so I expect we'll be working on it very soon.

**Closed by samselikoff** 2018-06-21 17:57 UTC
Labels: Feature request

**Comment by happyvig** [comment] 2019-06-13 03:19
The above mentioned link is broken.
Right one : https://github.com/samselikoff/ember-cli-mirage/issues/1411

**Comment by jayzhou3** [comment] 2019-08-20 18:11
> Just hit this issue as well. Spent a bunch of time debugging, trying to determine the cause, and turns out fastboot breaks mirage here. Anyone have a fix in mind?

Yeah, same as you. I spend a lot of time and can't understand why fastboot won't event work for my app the mirage is broken once I change the content of the script
